# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 16:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='regions.Level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_osm_relation', models.BooleanField(default=False, verbose_name='Is an OSM relation?')),
                ('osm_tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='OSM Tags')),
                ('osm_relation_id', models.IntegerField(blank=True, null=True, verbose_name='OSM Relation ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='regions.Level')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='regions.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
