# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 16:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('icon', models.ImageField(upload_to='category/icons/%Y/%m/%d/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('markdown_content', models.TextField(blank=True, verbose_name='Content')),
                ('html_content', models.TextField(editable=False, null=True)),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='This field will be updated with the content of latitude and longitude fields', null=True, srid=4326)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.Category')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='regions.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
